package com.ecollege.prospero.wsdl.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Jul 27 16:04:01 MDT 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://delivery.wsdl.prospero.ecollege.com", name = "DeliveryServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.ecollege.prospero.wsdl.delivery.xsd.ObjectFactory.class})
public interface DeliveryServicePortType {

    @WebResult(name = "return", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
    @Action(input = "urn:deliver", output = "urn:deliverResponse")
    @RequestWrapper(localName = "deliver", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com", className = "com.ecollege.prospero.wsdl.delivery.Deliver")
    @WebMethod(action = "urn:deliver")
    @ResponseWrapper(localName = "deliverResponse", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com", className = "com.ecollege.prospero.wsdl.delivery.DeliverResponse")
    public com.ecollege.prospero.wsdl.delivery.xsd.DeliveryResponse deliver(
        @WebParam(name = "messageType", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        java.lang.String messageType,
        @WebParam(name = "messageId", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        java.lang.String messageId,
        @WebParam(name = "attemptId", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        java.lang.String attemptId,
        @WebParam(name = "authenticationToken", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        java.lang.String authenticationToken,
        @WebParam(name = "authenticationDelimiter", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        java.lang.String authenticationDelimiter,
        @WebParam(name = "payload", targetNamespace = "http://delivery.wsdl.prospero.ecollege.com")
        byte[] payload
    ) throws Exception;
}
