#!/bin/sh

. "`dirname $0`/../deploy/scripts/always_included.sh"

ORIG_PATH=`pwd`
cd `dirname $0`
cd ..

ME=`basename $0`



HOST=$1

if [ "x" = "x$HOST" ]
then
  #HOSTNAME=`hostname`
  #FQDN=`hostname -f`
  PNODE=prospero@$FQDN
  echo "Prospero node name not specified, defaulting to $PNODE\n"
else
  PNODE=$HOST
fi



/opt/prospero/sbin/upgrade-principal-schema.escript "$PNODE"

cd $ORIG_PATH

