#!/bin/sh

. "`dirname $0`/../deploy/scripts/always_included.sh"

ORIG_PATH=`pwd`
cd `dirname $0`
cd ..

ME=`basename $0`



CALLBACK=$1
TAGS=$2
P_ID=$3
WSDL_URI=$4
HOST=$5

USAGE="Usage: $ME CallbackUrl Tags PrincipalId WsdlUri ProsperoNode"

if [ "x" = "x$P_ID" ]
then
  echo "Please specify the PrincipalId\n$USAGE"
  exit 1
fi

if [ "x" = "x$TAGS" ]
then
  echo "Please specify the Tags\n$USAGE"
  exit 1
fi

if [ "x" = "x$HOST" ]
then
  HOSTNAME=`hostname`
  FQDN=`hostname -f`
  PNODE=prospero@$FQDN
  echo "Prospero node name not specified, defaulting to $PNODE\n"
else
  PNODE=$HOST
fi



erl -pa ebin -name rotate -setcookie "${PROSPERO_ERLANG_COOKIE}" -noinput -hidden -eval "pe_remote:create_subscription('$PNODE',\"$CALLBACK\",\"$TAGS\",\"$P_ID\", \"$WSDL_URI\")."

cd $ORIG_PATH
