#!/bin/sh

. "`dirname $0`/../deploy/scripts/always_included.sh"

ORIG_PATH=`pwd`
cd `dirname $0`
cd ..

ME=`basename $0`


HOST=$1

USAGE="Usage: $ME ProsperoNode"


if [ "x" = "x$HOST" ]
then
  #HOSTNAME=`hostname`
  #FQDN=`hostname -f`
  PNODE=prospero@$FQDN
  echo "Prospero node name not specified, defaulting to $PNODE\n"
else
  PNODE=$HOST
fi


erl -pa ebin -name rotate -setcookie "${PROSPERO_ERLANG_COOKIE}" -noinput -hidden -eval "pe_remote:broker_status('$PNODE')."

cd $ORIG_PATH
