#!/bin/sh

. "`dirname $0`/../deploy/scripts/always_included.sh"

ORIG_PATH=`pwd`
cd `dirname $0`
cd ..

ME=`basename $0`



P_ID=$1
P_NAME=$2
P_TAGS=$3
P_MT_SUB_REQ=$4
P_SECRET=$5
P_REALM=$6
P_URL_MASK=$7
HOST=$8

USAGE="Usage: $ME PrincipalId FriendlyName EnforcedContextTagsCommaDelim IsMessageTypeRequiredForAllSubscriptions(true|false) SecretKey Realm DeliveryUrlMask ProsperoNode"

if [ "x" = "x$P_ID" ]
then
  echo "Please specify the PrincipalId\n$USAGE"
  exit 1
fi

if [ "x" = "x$P_NAME" ]
then
  echo "Please specify the FriendlyName\n$USAGE"
  exit 1
fi

if [ "x" = "x$P_MT_SUB_REQ" ]
then
  echo "Please specify the IsMessageTypeRequiredForAllSubscriptions\n$USAGE"
  exit 1
fi

if [ "x" = "x$P_SECRET" ]
then
  P_SECRET="undefined"
  echo "A secret key was not specified, one will be generated.\n"
fi

if [ "x" = "x$P_REALM" ]
then
  P_REALM="*"
  echo "A realm was not specified, using *.\n"
fi

if [ "x" = "x$P_URL_MASK" ]
then
  P_URL_MASK="*"
  echo "A delivery url mask was not specified, using *.\n"
fi

if [ "x" = "x$HOST" ]
then
  #HOSTNAME=`hostname`
  #FQDN=`hostname -f`
  PNODE=prospero@$FQDN
  echo "Prospero node name not specified, defaulting to $PNODE\n"
else
  PNODE=$HOST
fi



erl -pa ebin -name rotate -setcookie "${PROSPERO_ERLANG_COOKIE}" -noinput -hidden -eval "pe_remote:create_principal('$PNODE',\"$P_ID\",\"$P_NAME\",\"$P_TAGS\",$P_MT_SUB_REQ,\"$P_SECRET\",\"$P_REALM\",\"$P_URL_MASK\")."

cd $ORIG_PATH
