%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('p:DeliveryResponse', {anyAttribs, 'confirmationNumber'}).
-record('p:reqType', {anyAttribs, 'messageType', 'messageId', 'attemptId', 'authenticationToken', 'authenticationDelimiter', 'payloadContentType', 'payload'}).
-record('p:respType', {anyAttribs, 'return'}).
-record('soap:Body', {anyAttribs, choice}).
-record('soap:Envelope', {anyAttribs, 'Header', 'Body', choice}).
-record('soap:Fault', {anyAttribs, 'faultcode', 'faultstring', 'faultactor', 'detail'}).
-record('soap:Header', {anyAttribs, choice}).
-record('soap:detail', {anyAttribs, choice}).
